#!/usr/bin/env python3
"""Regenerate the foot [regex:emoji] pattern from an emoji database.

foot compiles the pattern with glibc's regcomp(REG_EXTENDED), which:

  * treats \\uXXXX, \\xHH and octal escapes as literal ASCII text (they are
    not supported), and
  * rejects multibyte character ranges under the C.UTF-8 locale
    (REG_ECOLLATE, "Invalid collation character"), which is the locale a
    foot launched from a desktop environment typically ends up in.

So the pattern is written with real UTF-8 literals only, and contains no
ranges at all. It is locale-independent and matches exactly the characters
found in the given emoji database, grouped so that foot labels one grapheme
cluster per match:

  keycap      [0-9#*] <FE0F> <20E3>
  flag pair   [regional][regional]
  subdivision <1F3F4> [tag letter]+ <E007F>
  cluster     R ([VS]|[SKIN])* (<ZWJ> R ([VS]|[SKIN])*)*

where R is a single character class of every database character that is not
ASCII, not a regional indicator, not a skin-tone modifier, and not a ZWJ /
variation-selector / keycap-join continuation character.

The England/Scotland/Wales flags are <1F3F4> plus tag letters from the Unicode
tag block plus a cancel tag, all of which are invisible formatting characters.
They get their own alternative and are excluded from R, so that a full flag
matches as one span and a lone tag character -- which has no visible width of
its own -- matches nothing at all. The tag block is written out in full rather
than derived from the database so the flags work with any database.
"""

import argparse
import json
import os
import sys

REGIONAL = range(0x1F1E6, 0x1F200)
SKIN = range(0x1F3FB, 0x1F400)
ZWJ = 0x200D
VS = (0xFE0E, 0xFE0F, 0x20E3)
KEYCAP_JOIN = (0xFE0F, 0x20E3)

# The subdivision flags (England/Scotland/Wales) are the black flag followed by
# tag letters from the Unicode tag block and terminated by the cancel tag. Both
# halves are default-ignorable formatting characters, so they are held out of
# the catch-all class R and given a shape of their own.
SUBDIVISION = 0x1F3F4
TAG_LETTER = range(0xE0061, 0xE007F)
CANCEL_TAG = 0xE007F


def read_entries(path):
    with open(path, encoding="utf-8") as fp:
        return [item["e"] for item in json.load(fp)]


def foot_config_dir():
    xdg = os.environ.get("XDG_CONFIG_HOME")
    if xdg:
        return xdg
    return os.path.join(os.path.expanduser("~"), ".config")


def build_pattern(entries):
    cps = {ord(ch) for em in entries for ch in em}
    core = sorted(
        cps
        - set(range(0x80))
        - set(REGIONAL)
        - set(SKIN)
        - {ZWJ}
        - set(VS)
        - set(KEYCAP_JOIN)
        - set(TAG_LETTER)
        - {CANCEL_TAG}
    )

    def char_class(cps):
        return "[" + "".join(chr(c) for c in cps) + "]"

    r_class = char_class(core)
    regional_class = char_class(REGIONAL)
    skin_class = char_class(SKIN)
    vs_class = char_class(VS)
    tag_class = char_class(TAG_LETTER)
    keycap_join = "".join(chr(c) for c in KEYCAP_JOIN)

    # "one or more" tag letters, then the mandatory cancel tag: exactly the
    # shape Unicode gives the subdivision flags. A tag run with no cancel tag,
    # or a bare tag character, is deliberately not a match.
    subdivision = chr(SUBDIVISION) + tag_class + "+" + chr(CANCEL_TAG)

    base = r_class + "(" + vs_class + "|" + skin_class + ")*"
    return (
        "([0-9#*]" + keycap_join
        + "|" + regional_class + regional_class
        + "|" + subdivision
        + "|" + base + "(" + chr(ZWJ) + base + ")*"
        + ")"
    )


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--db", default="/usr/share/omarchy/shell/plugins/emojis/emojis.json", help="emoji database JSON (default: omarchy's)")
    ap.add_argument("-o", "--output", default=None,
                    help="write the [regex:emoji] ini here (default: foot's config directory, "
                         "$XDG_CONFIG_HOME/foot or ~/.config/foot, as foot-emoji-regex.ini); use - for stdout")
    ap.add_argument("--launch", default=os.path.expanduser("~/.local/bin/foot-emoji-name"),
                    help="launcher command for the regex binding (default: ~/.local/bin/foot-emoji-name)")
    ap.add_argument("--keybinding", default="Control+Shift+e",
                    help="hotkey to bind to regex-launch (default: Control+Shift+e)")
    args = ap.parse_args()

    pattern = build_pattern(read_entries(args.db))

    out = args.output
    if out is None:
        out = os.path.join(foot_config_dir(), "foot", "foot-emoji-regex.ini")

    if out == "-":
        print(pattern)
        return 0

    header = (
        "# Generated by tools/generate.py from " + args.db + ". Written with UTF-8\n"
        "# literals only; glibc rejects \\uXXXX/\\xHH/octal escapes as literal text and\n"
        "# multibyte ranges (REG_ECOLLATE under C.UTF-8). One label covers one emoji.\n"
        "# This whole block is referenced from foot.ini with a single include= line;\n"
        "# regenerate with tools/generate.py (idempotent) and run foot -C afterwards.\n"
        "[regex:emoji]\n"
        "regex=" + pattern + "\n"
        "launch=" + args.launch + " ${match}\n"
        "\n"
        "[key-bindings]\n"
        "regex-launch=[emoji] " + args.keybinding + "\n"
    )
    # foot's config directory may not exist yet on a machine that has never
    # started foot, so create it rather than failing with ENOENT.
    parent = os.path.dirname(out)
    if parent:
        os.makedirs(parent, exist_ok=True)
    with open(out, "w", encoding="utf-8") as fp:
        fp.write(header)
    print("wrote %s (%d chars)" % (out, len(pattern)))
    return 0


if __name__ == "__main__":
    sys.exit(main())